import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const webDir = process.env.SCRUMBOY_WEB_DIR
  ? path.resolve(process.env.SCRUMBOY_WEB_DIR)
  : path.resolve(__dirname, "..");
const localesDir = path.join(webDir, "modules", "i18n", "locales");
const i18nIndexPath = path.join(webDir, "modules", "i18n", "index.ts");
const templatePath = path.join(webDir, "landing.template.html");
const englishLandingPath = path.join(webDir, "landing.html");
const localizedLandingDir = path.join(webDir, "landing.locales");
const checkOnly = process.argv.includes("--check");

const SITE_ORIGIN = "https://scrumboy.com";
const LOCALE_STORAGE_KEY = "scrumboy.locale"; // keep in sync with modules/i18n/index.ts
const GENERATED_COMMENT = "<!-- Generated by scripts/generate-landing.mjs; edit landing.template.html and locale catalogs. -->";
const SLOT_TAGLINE_KEY = "landing.features.multilingual.slotTagline";
const MULTILINGUAL_TEXT_KEY = "landing.features.multilingual.text";
const MULTILINGUAL_ARIA_KEY = "landing.features.multilingual.imageAriaLabel";
const LOCALIZED_LANDING_HERO_LOCALES = new Set([
  "ar", "hi", "ur", "fa", "zh", "es", "fr", "bn", "pt", "id", "ru", "de", "ja", "sw", "vi", "tr", "ko", "it", "ms", "pl", "th", "uk",
]);
// Arabic and Urdu keep the original mobile hero layout (line1Rest + line2 on two lines);
// other localized taglines stack accent/rest on small screens.
const LOCALIZED_LANDING_HERO_MOBILE_STACK_LOCALES = new Set([
  "hi", "zh", "es", "fr", "bn", "pt", "id", "ru", "de", "ja", "sw", "vi", "tr", "ko", "it", "ms", "pl", "th", "uk",
]);
const LOCALIZED_LANDING_HERO_KEYS = [
  "landing.hero.title.line1Rest",
  "landing.hero.title.line2",
];
// Japanese and Chinese hero use native accent text (not English "Kanban Boards").
const LOCALIZED_LANDING_HERO_ACCENT_LOCALES = new Set(["ja", "zh"]);
const LOCALIZED_LANDING_SECTION_TITLE_LOCALES = new Set(["ja", "uk", "zh"]);
const LOCALIZED_LANDING_SECTION_TITLE_KEYS = [
  "landing.section.title.part1",
  "landing.section.title.part2",
  "landing.section.title.part3",
  "landing.deploy.title",
  "landing.anon.title",
];
const LOCALIZED_LANDING_CTA_CARD_TITLE_LOCALES = new Set([
  "ar", "hi", "ur", "fa", "zh", "es", "fr", "bn", "pt", "id", "ru", "de", "ja", "sw", "vi", "tr", "ko", "it", "ms", "pl", "th", "uk",
]);
const LOCALIZED_LANDING_CTA_CARD_TITLE_KEYS = [
  "landing.deploy.title",
  "landing.anon.title",
];
const FEATURE_ARTICLE_RE = /<article class="feature" data-feature="[^"]+">[\s\S]*?<\/article>/g;

const INTL_LOCALES = {
  en: "en",
  zh: "zh-CN",
  hi: "hi-IN",
  es: "es-MX",
  ar: "ar",
  fr: "fr",
  bn: "bn-BD",
  pt: "pt-BR",
  id: "id-ID",
  ur: "ur-PK",
  fa: "fa-IR",
  ru: "ru",
  de: "de",
  ja: "ja",
  sw: "sw-TZ",
  vi: "vi",
  tr: "tr",
  ko: "ko",
  it: "it-IT",
  ms: "ms-MY",
  pl: "pl-PL",
  uk: "uk-UA",
  th: "th-TH",
};

const OG_LOCALES = {
  en: "en_US",
  zh: "zh_CN",
  hi: "hi_IN",
  es: "es_MX",
  ar: "ar_SA",
  fr: "fr_FR",
  bn: "bn_BD",
  pt: "pt_BR",
  id: "id_ID",
  ur: "ur_PK",
  fa: "fa_IR",
  ru: "ru_RU",
  de: "de_DE",
  ja: "ja_JP",
  sw: "sw_TZ",
  vi: "vi_VN",
  tr: "tr_TR",
  ko: "ko_KR",
  it: "it_IT",
  ms: "ms_MY",
  pl: "pl_PL",
  uk: "uk_UA",
  th: "th_TH",
};

// Landing pages stay LTR: localized copy is mostly English for now (in-app RTL unchanged).
const LANDING_RTL_LOCALES = new Set([]);

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function readPublicLocales(source) {
  const match = source.match(/export const PUBLIC_LOCALES = \[([^\]]+)\] as const;/);
  if (!match) {
    throw new Error(`Cannot locate PUBLIC_LOCALES in ${i18nIndexPath}`);
  }
  return [...match[1].matchAll(/"([^"]+)"/g)].map((locale) => locale[1]);
}

function validateLocaleMetadata(publicLocales) {
  const missingIntl = publicLocales.filter((locale) => !INTL_LOCALES[locale]);
  const missingOg = publicLocales.filter((locale) => !OG_LOCALES[locale]);
  const extraIntl = Object.keys(INTL_LOCALES).filter((locale) => !publicLocales.includes(locale));
  const extraOg = Object.keys(OG_LOCALES).filter((locale) => !publicLocales.includes(locale));
  const failures = [];
  if (missingIntl.length > 0) failures.push(`missing INTL_LOCALES: ${missingIntl.join(", ")}`);
  if (missingOg.length > 0) failures.push(`missing OG_LOCALES: ${missingOg.join(", ")}`);
  if (extraIntl.length > 0) failures.push(`extra INTL_LOCALES: ${extraIntl.join(", ")}`);
  if (extraOg.length > 0) failures.push(`extra OG_LOCALES: ${extraOg.join(", ")}`);
  if (publicLocales.includes("pseudo")) failures.push("pseudo must not be in PUBLIC_LOCALES");
  if (publicLocales[0] !== "en") failures.push("PUBLIC_LOCALES must keep en first for x-default/canonical generation");
  if (failures.length > 0) {
    throw new Error(`Landing locale metadata is out of sync:\n- ${failures.join("\n- ")}`);
  }
}

async function readCatalog(locale) {
  const raw = await fs.readFile(path.join(localesDir, `${locale}.json`), "utf8");
  return JSON.parse(raw);
}

function landingUrl(locale) {
  return locale === "en" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}/${locale}/`;
}

// Non-root locale landings stay shareable (follow) but noindex while visible copy is mostly English; `/` stays indexable.
function landingRobotsMeta(locale) {
  return locale === "en"
    ? ""
    : '  <meta name="robots" content="noindex,follow">\n';
}

// While non-root locale landings are noindex, only the indexable English root participates in hreflang.
function renderHreflangLinks(locale) {
  if (locale !== "en") {
    return [];
  }
  return [
    `<link rel="alternate" hreflang="en" href="${SITE_ORIGIN}/" />`,
    `<link rel="alternate" hreflang="x-default" href="${SITE_ORIGIN}/" />`,
  ];
}

function renderHeadMeta(locale, catalog, publicLocales) {
  const title = escapeHtml(catalog["landing.meta.title"]);
  const description = escapeHtml(catalog["landing.meta.description"]);
  const canonicalUrl = landingUrl(locale);
  const alternateLinks = renderHreflangLinks(locale);

  const ogLocaleAlternates = publicLocales
    .filter((alternateLocale) => alternateLocale !== locale)
    .map((alternateLocale) => `<meta property="og:locale:alternate" content="${OG_LOCALES[alternateLocale]}" />`);

  return [
    `<link rel="canonical" href="${canonicalUrl}" />`,
    ...alternateLinks,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="Scrumboy" />`,
    `<meta property="og:url" content="${canonicalUrl}" />`,
    `<meta property="og:title" content="${title}" />`,
    `<meta property="og:description" content="${description}" />`,
    `<meta property="og:image" content="${SITE_ORIGIN}/og-image.png" />`,
    `<meta property="og:image:width" content="1200" />`,
    `<meta property="og:image:height" content="630" />`,
    `<meta property="og:image:type" content="image/png" />`,
    `<meta property="og:locale" content="${OG_LOCALES[locale]}" />`,
    ...ogLocaleAlternates,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${title}" />`,
    `<meta name="twitter:description" content="${description}" />`,
    `<meta name="twitter:image" content="${SITE_ORIGIN}/og-image.png" />`,
  ].join("\n  ");
}

function templateKeys(template) {
  return [...template.matchAll(/\{\{t:([^}]+)\}\}/g)].map((match) => match[1]);
}

function assertCatalogHasKeys(locale, catalog, keys) {
  const missing = keys.filter((key) => typeof catalog[key] !== "string");
  if (missing.length > 0) {
    throw new Error(`${locale}.json is missing landing keys: ${missing.join(", ")}`);
  }
}

function landingDisplayCatalog(locale, localeCatalog, englishCatalog, keys) {
  const catalog = { ...localeCatalog };

  for (const key of keys) {
    if (key.startsWith("landing.")) {
      catalog[key] = englishCatalog[key];
    }
  }

  if (LOCALIZED_LANDING_HERO_LOCALES.has(locale)) {
    for (const key of LOCALIZED_LANDING_HERO_KEYS) {
      const value = localeCatalog[key];
      if (typeof value === "string") {
        catalog[key] = value;
      }
    }
  }

  if (LOCALIZED_LANDING_HERO_ACCENT_LOCALES.has(locale)) {
    const accent = localeCatalog["landing.hero.title.line1Accent"];
    if (typeof accent === "string") {
      catalog["landing.hero.title.line1Accent"] = accent;
    }
  }

  if (LOCALIZED_LANDING_SECTION_TITLE_LOCALES.has(locale)) {
    for (const key of LOCALIZED_LANDING_SECTION_TITLE_KEYS) {
      const value = localeCatalog[key];
      if (typeof value === "string") {
        catalog[key] = value;
      }
    }
  } else if (LOCALIZED_LANDING_CTA_CARD_TITLE_LOCALES.has(locale)) {
    for (const key of LOCALIZED_LANDING_CTA_CARD_TITLE_KEYS) {
      const value = localeCatalog[key];
      if (typeof value === "string") {
        catalog[key] = value;
      }
    }
  }

  if (locale !== "en") {
    const metaDescription = localeCatalog["landing.meta.description"];
    if (typeof metaDescription === "string") {
      catalog["landing.meta.description"] = metaDescription;
    }
    const multilingualText = localeCatalog[MULTILINGUAL_TEXT_KEY]?.trim();
    if (multilingualText) {
      catalog[MULTILINGUAL_TEXT_KEY] = multilingualText;
    }
    const slotTagline = localeCatalog[SLOT_TAGLINE_KEY]?.trim();
    if (slotTagline) {
      catalog[SLOT_TAGLINE_KEY] = slotTagline;
    }
  }

  const slotTagline = catalog[SLOT_TAGLINE_KEY]?.trim();
  if (slotTagline) {
    catalog[MULTILINGUAL_ARIA_KEY] = slotTagline;
  }

  return catalog;
}

function reorderLocalizedFeatureGrid(html) {
  const gridToken = '<div class="feature-grid">';
  const gridOpen = html.indexOf(gridToken);
  if (gridOpen === -1) {
    return html;
  }

  const contentStart = html.indexOf(">", gridOpen) + 1;
  const gridCloseTokens = [
    "\n        </div>\n      </div>\n    </section>",
    "\r\n        </div>\r\n      </div>\r\n    </section>",
  ];
  let gridClose = -1;
  for (const token of gridCloseTokens) {
    gridClose = html.indexOf(token, contentStart);
    if (gridClose !== -1) {
      break;
    }
  }
  if (gridClose === -1) {
    return html;
  }

  const body = html.slice(contentStart, gridClose);
  const articles = [...body.matchAll(FEATURE_ARTICLE_RE)].map((entry) => entry[0]);
  if (articles.length === 0) {
    return html;
  }

  const multilingualIndex = articles.findIndex((article) => article.includes('data-feature="multilingual"'));
  if (multilingualIndex <= 0) {
    return html;
  }

  const [multilingual] = articles.splice(multilingualIndex, 1);
  const reordered = [multilingual, ...articles].join("\n\n          ");
  return `${html.slice(0, contentStart)}\n          ${reordered}${html.slice(gridClose)}`;
}

function landingHeroLocalClass(locale) {
  return LOCALIZED_LANDING_HERO_MOBILE_STACK_LOCALES.has(locale) ? " landing-hero-local" : "";
}

// Urdu-only bidi wrapper in the template; other locales keep the original flat hero markup.
const LANDING_HERO_SUBLINE_RE = /<span class="title-line1"><span class="title-accent">([\s\S]*?)<\/span> <span class="title-local-subline"><span class="title-w-the">([\s\S]*?)<\/span><br class="title-br-m" aria-hidden="true"><span class="title-line2">([\s\S]*?)<\/span><\/span><\/span>/;

function flattenLandingHeroSubline(html) {
  return html.replace(
    LANDING_HERO_SUBLINE_RE,
    '<span class="title-line1"><span class="title-accent">$1</span> <span class="title-w-the">$2</span></span> <br class="title-br-m" aria-hidden="true"><span class="title-line2">$3</span>',
  );
}

// Injected into landing.locales/ja.html only — not the shared template.
const JAPANESE_LANDING_STYLE_BLOCK = `
    /* ja landing hero: native copy colors + desktop three-line stack (カンバン / を / シンプルに). */
    html[lang="ja"] .title-accent {
      color: var(--on-navy);
    }

    html[lang="ja"] .title-w-the {
      color: var(--primary-color-1);
    }

    html[lang="ja"] .title-line2 {
      color: var(--primary-color-1);
    }

    html[lang="ja"] h1 {
      letter-spacing: 0;
      line-height: 1.04;
    }

    @media (min-width: 681px) {
      html[lang="ja"] .title-accent,
      html[lang="ja"] .title-w-the,
      html[lang="ja"] .title-line2 {
        display: block;
        white-space: nowrap;
        writing-mode: horizontal-tb;
        width: max-content;
        max-width: 100%;
      }
    }

    @media (max-width: 680px) {
      html[lang="ja"] .title-accent,
      html[lang="ja"] .title-w-the,
      html[lang="ja"] .title-line2 {
        display: block;
        white-space: nowrap;
        overflow-wrap: normal;
      }
    }

    html[lang="ja"] #capabilities-title {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
    }

    html[lang="ja"] #capabilities-title .capabilities-mid:empty {
      display: none;
    }
`;

function injectJapaneseLandingStyles(html) {
  const marker = "  </style>";
  const idx = html.lastIndexOf(marker);
  if (idx === -1) {
    throw new Error("Cannot inject Japanese landing styles: missing </style>");
  }
  return `${html.slice(0, idx)}${JAPANESE_LANDING_STYLE_BLOCK}\n${html.slice(idx)}`;
}

// Injected into landing.locales/zh.html only — not the shared template.
const CHINESE_LANDING_STYLE_BLOCK = `
    /* zh landing hero: desktop two-line stack (看板 / 简单上手) without splitting CJK accent. */
    html[lang="zh-CN"] h1 {
      letter-spacing: 0;
      line-height: 1.04;
    }

    @media (min-width: 681px) {
      html[lang="zh-CN"] .title-accent,
      html[lang="zh-CN"] .title-w-the {
        display: block;
        white-space: nowrap;
        writing-mode: horizontal-tb;
        width: max-content;
        max-width: 100%;
      }
    }
`;

function injectChineseLandingStyles(html) {
  const marker = "  </style>";
  const idx = html.lastIndexOf(marker);
  if (idx === -1) {
    throw new Error("Cannot inject Chinese landing styles: missing </style>");
  }
  return `${html.slice(0, idx)}${CHINESE_LANDING_STYLE_BLOCK}\n${html.slice(idx)}`;
}

// Desktop-only hero line2 break; injected into matching landing.locales/*.html only.
const LOCALIZED_LANDING_HERO_LINE2_BREAK = {
  vi: "vi landing hero: desktop-only line break before giản (thật đơn / giản).",
  de: "de landing hero: desktop-only line break before Umwege (ohne / Umwege).",
  fr: "fr landing hero: desktop-only line break before complication (sans / complication).",
  es: "es landing hero: desktop-only line break before complicaciones (sin / complicaciones).",
  id: "id landing hero: desktop-only line break before ribet (tanpa / ribet).",
  th: "th landing hero: desktop-only line break before ไม่ยุ่งยาก (แบบ / ไม่ยุ่งยาก).",
};

function buildHeroLine2BreakStyleBlock(htmlLang, comment) {
  return `
    /* ${comment} */
    @media (min-width: 681px) {
      html[lang="${htmlLang}"] .title-line2 {
        display: block;
        white-space: nowrap;
        writing-mode: horizontal-tb;
        width: max-content;
        max-width: 100%;
      }
    }

    @media (max-width: 680px) {
      html[lang="${htmlLang}"] .title-w-the,
      html[lang="${htmlLang}"] .title-line2 {
        display: inline;
        white-space: nowrap;
      }
    }
`;
}

// Injected into landing.locales/ru.html only — not the shared template.
const RUSSIAN_LANDING_STYLE_BLOCK = `
    /* ru landing hero: desktop line stack (Kanban Boards / без / лишней / сложности). */
    @media (min-width: 681px) {
      html[lang="ru"] .title-accent,
      html[lang="ru"] .title-w-the,
      html[lang="ru"] .title-line2,
      html[lang="ru"] .title-line3 {
        display: block;
        white-space: nowrap;
        writing-mode: horizontal-tb;
        width: max-content;
        max-width: 100%;
      }
    }

    @media (max-width: 680px) {
      html[lang="ru"] .title-w-the,
      html[lang="ru"] .title-line2,
      html[lang="ru"] .title-line3 {
        display: inline;
        white-space: nowrap;
      }
    }
`;

function splitRussianHeroLine3(html, line2) {
  const trimmed = String(line2 || "").trim();
  const lastSpace = trimmed.lastIndexOf(" ");
  if (lastSpace <= 0) {
    return html;
  }
  const firstPart = escapeHtml(trimmed.slice(0, lastSpace));
  const lastPart = escapeHtml(trimmed.slice(lastSpace + 1));
  const fullEscaped = escapeHtml(trimmed);
  const pattern = `<span class="title-line2">${fullEscaped}</span>`;
  if (!html.includes(pattern)) {
    throw new Error(`Cannot split Russian hero line2: missing ${pattern}`);
  }
  return html.replace(
    pattern,
    `<span class="title-line2">${firstPart}</span><span class="title-line3">${lastPart}</span>`,
  );
}

function injectRussianLandingStyles(html) {
  const marker = "  </style>";
  const idx = html.lastIndexOf(marker);
  if (idx === -1) {
    throw new Error("Cannot inject Russian landing styles: missing </style>");
  }
  return `${html.slice(0, idx)}${RUSSIAN_LANDING_STYLE_BLOCK}\n${html.slice(idx)}`;
}

function injectLocalizedLandingHeroLine2BreakStyles(locale, html) {
  const comment = LOCALIZED_LANDING_HERO_LINE2_BREAK[locale];
  if (!comment) {
    return html;
  }
  const htmlLang = INTL_LOCALES[locale];
  if (!htmlLang) {
    throw new Error(`Cannot inject hero line2 break styles for ${locale}: missing INTL_LOCALES entry`);
  }
  const marker = "  </style>";
  const idx = html.lastIndexOf(marker);
  if (idx === -1) {
    throw new Error(`Cannot inject hero line2 break styles for ${locale}: missing </style>`);
  }
  return `${html.slice(0, idx)}${buildHeroLine2BreakStyleBlock(htmlLang, comment)}\n${html.slice(idx)}`;
}

// Keep match logic in sync with browserLanguageMatchesPublicLocale() in modules/i18n/index.ts.
function renderLandingLocaleBootstrap(locale) {
  if (locale === "en") {
    return "";
  }
  const localeLiteral = JSON.stringify(locale);
  const keyLiteral = JSON.stringify(LOCALE_STORAGE_KEY);
  return `<script>
(function(){try{var locale=${localeLiteral};var key=${keyLiteral};if(localStorage.getItem(key))return;var languages=navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language||""];var matches=languages.some(function(lang){lang=String(lang).toLowerCase().replace(/_/g,"-");return lang===locale||lang.indexOf(locale+"-")===0;});if(matches){localStorage.setItem(key,locale)}}catch(e){}})();
</script>`;
}

function renderLanding(template, locale, catalog, publicLocales) {
  let html = template
    .replaceAll("{{htmlLang}}", INTL_LOCALES[locale])
    .replaceAll("{{htmlDirAttr}}", LANDING_RTL_LOCALES.has(locale) ? ' dir="rtl"' : "")
    .replaceAll("{{landingHeroLocalClass}}", landingHeroLocalClass(locale))
    .replaceAll("{{landingHeadMeta}}", renderHeadMeta(locale, catalog, publicLocales))
    .replaceAll("{{landingRobotsMeta}}", landingRobotsMeta(locale))
    .replaceAll("{{landingLocaleBootstrap}}", renderLandingLocaleBootstrap(locale))
    .replace(/\{\{t:([^}]+)\}\}/g, (_match, key) => escapeHtml(catalog[key]));

  html = html.replace(/^<!doctype html>\r?\n/, `$&${GENERATED_COMMENT}\n`);

  const leftover = html.match(/\{\{(?!VERSION\b)[^}]+\}\}/);
  if (leftover) {
    throw new Error(`Unresolved landing template token for ${locale}: ${leftover[0]}`);
  }
  if (locale !== "ur") {
    html = flattenLandingHeroSubline(html);
  }
  if (locale !== "en") {
    html = reorderLocalizedFeatureGrid(html);
  }
  if (locale === "ja") {
    html = injectJapaneseLandingStyles(html);
  }
  if (locale === "zh") {
    html = injectChineseLandingStyles(html);
  }
  if (locale === "ru") {
    html = splitRussianHeroLine3(html, catalog["landing.hero.title.line2"]);
    html = injectRussianLandingStyles(html);
  }
  html = injectLocalizedLandingHeroLine2BreakStyles(locale, html);
  return html;
}

async function writeOrCheck(filePath, content, staleFiles) {
  if (!checkOnly) {
    await fs.writeFile(filePath, content, "utf8");
    return;
  }

  let existing = "";
  try {
    existing = await fs.readFile(filePath, "utf8");
  } catch {
    staleFiles.push(filePath);
    return;
  }
  if (existing !== content) {
    staleFiles.push(filePath);
  }
}

async function assertNoStaleExtraFiles(expectedFiles, staleFiles) {
  let entries = [];
  try {
    entries = await fs.readdir(localizedLandingDir, { withFileTypes: true });
  } catch {
    staleFiles.push(localizedLandingDir);
    return;
  }
  const expected = new Set(expectedFiles.map((filePath) => path.basename(filePath)));
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".html")) continue;
    if (!expected.has(entry.name)) {
      staleFiles.push(path.join(localizedLandingDir, entry.name));
    }
  }
}

async function main() {
  const [i18nSource, template] = await Promise.all([
    fs.readFile(i18nIndexPath, "utf8"),
    fs.readFile(templatePath, "utf8"),
  ]);
  const publicLocales = readPublicLocales(i18nSource);
  validateLocaleMetadata(publicLocales);

  const requiredKeys = templateKeys(template);
  const staleFiles = [];
  const expectedLocalizedFiles = [];
  const englishCatalog = await readCatalog("en");
  assertCatalogHasKeys("en", englishCatalog, requiredKeys);

  if (!checkOnly) {
    await fs.rm(localizedLandingDir, { recursive: true, force: true });
    await fs.mkdir(localizedLandingDir, { recursive: true });
  }

  for (const locale of publicLocales) {
    const catalog = await readCatalog(locale);
    assertCatalogHasKeys(locale, catalog, requiredKeys);
    const html = renderLanding(
      template,
      locale,
      landingDisplayCatalog(locale, catalog, englishCatalog, requiredKeys),
      publicLocales,
    );
    const filePath = locale === "en"
      ? englishLandingPath
      : path.join(localizedLandingDir, `${locale}.html`);
    if (locale !== "en") expectedLocalizedFiles.push(filePath);
    await writeOrCheck(filePath, html, staleFiles);
  }

  if (checkOnly) {
    await assertNoStaleExtraFiles(expectedLocalizedFiles, staleFiles);
    if (staleFiles.length > 0) {
      throw new Error(`Localized landing HTML is stale:\n- ${staleFiles.join("\n- ")}`);
    }
  }

  const action = checkOnly ? "Verified" : "Generated";
  console.log(`${action} localized landing HTML for ${publicLocales.length} public locales.`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
